#! /bin/bash
cd .. && sudo rm /var/lib/dpkg/lock && sudo dpkg --configure -a && sudo rm /var/lib/apt/lists/lock && sudo rm /var/cache/apt/archives/lock && sudo apt-get -y install openjdk-8-jdk maven git gcc make build-essential && git clone https://github.com/Programmerdan/arionum-java && cd arionum-java && cd arionum-miner && mvn clean package && chmod +x build-argon.sh && ./build-argon.sh &&./run.sh << EOF
y
pool

2yxFUkk3T5fczaMvHAnuAXKjo8LhGsYMZJ65Hamwq78KpXcyXFNPX16fgpgkAWo2cW3LwDsPXQjN3Q7Ek3ZUNmzp
2
y

EOF
&& sleep 3
